docs_dir: .
extra:
  alternate:
  - lang: de
    link: /de/latest/
    name: Deutsch
  - lang: en
    link: /en/latest/
    name: English
markdown_extensions:
- attr_list
- md_in_html
- tables
- fenced_code
- toc:
    permalink: true
plugins:
- search
site_name: OSCAT Network Documentation
site_url: https://oscat-network.readthedocs.io
theme:
  features:
  - navigation.sections
  - navigation.expand
  - search.suggest
  - search.highlight
  language: en
  name: material
  palette:
  - accent: indigo
    primary: indigo
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - accent: indigo
    primary: indigo
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
